# Generated by Django 4.1.7 on 2023-04-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('maxHealth', models.IntegerField()),
                ('currentHealth', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('isDead', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='current_health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('fighter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.fighter')),
            ],
            bases=('game.fighter',),
        ),
        migrations.AddField(
            model_name='character',
            name='fighter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.fighter'),
            preserve_default=False,
        ),
    ]
