# Generated by Django 4.1.7 on 2023-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_fighter_remove_character_current_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
