# Generated by Django 4.1.7 on 2023-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_character_dexterity_character_intelligence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pointsToSpend',
            field=models.IntegerField(default=0),
        ),
    ]
