# Generated by Django 4.1.7 on 2023-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_experience_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='experienceReward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='goldReward',
            field=models.IntegerField(default=0),
        ),
    ]
